spring.application.name=apicalendario
spring.datasource.url=jdbc:postgresql://localhost:5432/apicalendario
spring.datasource.username=postgres
spring.datasource.password=1037620530s

spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
